version: '2'
services:
  web:
    image: sincco/php:74
    env_file: .env
    volumes:
      - ./src:/var/www/html/
      - ./.docker/hosts/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.docker/certs/certificado.crt:/etc/ssl/certs/certificado.crt
      - ./.docker/certs/certificado.key:/etc/ssl/private/certificado.key
    ports:
      - "${WEB_PORT}:80"
      - "${WEB_PORT_SSL}:443"
  db:
    image: mariadb:${MYSQL_VERSION}
    env_file: .env
    ports:
     - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    networks:
      - net
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "${MYADMIN_POR}:80"
    networks:
      - net      
  elasticsearch:
    image: elasticsearch:${ES_VERSION}
    env_file: .env
    ports:
      - "${ES_PORT_1}:9200"
      - "${ES_PORT_2}:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms${ES_MEMORY} -Xmx${ES_MEMORY}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./.docker/esdata:/usr/share/elasticsearch/data"
    networks:
      - net
  mailhog:
    image: mailhog/mailhog
    hostname: "mailhog"
    ports:
      - 1025
      - "${MAILHOG_PORT}:8025"
    networks:
      - net
networks:
  net:
    driver: bridge
volumes:
  dbdata:
    driver: local
